config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :reviews
  devise_for :users
  # resource:author
   resources :authors

  root "authors#index"


   devise_scope :user do
    authenticated :user do
    root 'author#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
     # root to: "devise/sessions#new"

  end
  
   # end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/author.rb
class Author < ApplicationRecord
	has_one_attached :image
    has_many :reviews
    belongs_to :user,:optional=>true
    belongs_to :category,:optional=>true
  
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_user!
  :load_and_authorize_resource

  def index
    @author = Author.all
  end
  def new
    @author = Author.new
  end
  def create
    @author = Author.new(book_params)

    if @author.save
            flash[:notice] = 'Book added!'  
      redirect_to @author
    else
      flash[:error] = 'Failed to add book!'   
      render new 
    end
  end

   def show
    @author = Author.find(params[:id])
  end



  def edit
    @author = Author.find(params[:id])
  end


  def update
    @author= Author.find(params[:id])

    if @author.update(book_params)
      redirect_to @author
    else
      render :edit
    end

  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy

    redirect_to root_path
  end



end
private

  def book_params
    params.require(:author).permit(:bookname,:authorname,:image)
  end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/edit.html.erb
	<h1>EDIT BOOKS</h1>

<%= form_with model: @author do |form| %>
  <div>
    <%= form.label :bookname %><br>
    <%= form.text_field :bookname %>
  </div>

  <div>
    <%= form.label :authorname %><br>
    <%= form.text_field :authorname %>
  </div>


  <div>

  <%= form.label :"image"%><br>
  <%= form.file_field :image %>
</div>
<br>

  <div>
    <%=form.submit "Update book" %>
  </div>
<% end %>

app/views/authors/index.html.erb
<h1>BOOKS</h1>

<ul>
  <% @author.each do |authors| %>
    <li>
      <h1> Book name:</h1><h4><%= authors.bookname %></h4><br>
      
     <h2> Author name:</h2><br><h4> <%= authors.authorname%></h4><br>
    </li>
    <li>
    
  <div class="card" style="width: 20rem;">
  <img class="card-img-top" src="<%= (url_for(authors.image))%>" alt="Good">
  <div class="card-body">
    <h5 class="card-title">images</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>

    <a href="/authors/1" class="btn btn-primary">Go to book</a>
  </div>
</div>

    </li>
    
</ul>
  <% end %>
    


<%= link_to "Create a new book", "/authors/new" %>
<br>

<% if user_signed_in? %> 
 <div> Welcome <%= current_user.email %> </div> 
  <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
<% else %>
  <%= button_to "Sign in", new_user_session_path %> 
<% end %>

app/views/authors/new.html.erb
	<h1>New BOOKS</h1>

<%= form_with model: @author do |form| %>
  <div>
    <%= form.label :bookname %><br>
    <%= form.text_field :bookname %>
  </div>

  <div>
    <%= form.label :authorname %><br>
    <%= form.text_field :authorname %>
  </div>

  <div>
    
  </div>
  

  <div>

  <%= form.label :"image"%><br>
  <%= form.file_field :image%>

  </div>

  <br>

  <div>
    <%=form.submit "Create book"%>
  </div>
<% end %>

app/views/authors/show.html.erb
<h1>Book name:<br><%= @author.bookname %></h1>
<!-- <br> -->
<h2>Author name:<br><%= @author.authorname %></h2>



    <div class="card" style="width: 20rem;">
  <img class="card-img-top" src="<%=(url_for(@author.image))%>" alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">images</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>







    <br>

     <%= link_to "Write a Review", new_review_path(@author) %>
  


<ul>
  <li><%= link_to "Edit book", edit_author_path(@author) %></li>
  <li><%= link_to "Destroy book", author_path(@author), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>